bd cv online app
CREATE TABLE  "PERSONA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(2000) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(2000) NOT NULL ENABLE, 
	"DNI" NUMBER(11,0) NOT NULL ENABLE, 
	"CUIT" NUMBER(14,0), 
	"ES_ALUMNO" NUMBER(1,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "PERSONA_DETALLE" 
   (	"ID_PERSONA" NUMBER NOT NULL ENABLE, 
	"ITEM" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(2000), 
	"TELEFONO" NUMBER, 
	"CELULAR" NUMBER, 
	"DIRECCION" VARCHAR2(2000), 
	"LINKEDIN" VARCHAR2(2000), 
	"FACEBOOK" VARCHAR2(2000), 
	"INSTAGRAM" VARCHAR2(2000)
   )
/
ALTER TABLE  "PERSONA_DETALLE" ADD CONSTRAINT "persona_fk" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES  "PERSONA" ("ID") ENABLE
/

CREATE TABLE  "PERSONA_EDUCACION" 
   (	"ID_PERSONA" NUMBER, 
	"ITEM" NUMBER, 
	"INSTITUCION" VARCHAR2(1000), 
	"TITULO" VARCHAR2(1000), 
	"DESCRIPCION" VARCHAR2(2000), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   )
/
ALTER TABLE  "PERSONA_EDUCACION" ADD CONSTRAINT "eval_educacion_persona_fk" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES  "PERSONA" ("ID") ENABLE
/

CREATE TABLE  "PERSONA_EXPERIENCIA" 
   (	"ID_PERSONA" NUMBER, 
	"ITEM" NUMBER, 
	"INSTITUCION" VARCHAR2(1000), 
	"EMPRESA" VARCHAR2(2000), 
	"ROL" VARCHAR2(1000), 
	"DESCRIPCION" VARCHAR2(2000), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   )
/
ALTER TABLE  "PERSONA_EXPERIENCIA" ADD CONSTRAINT "eval_experiencia_persona_fk" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES  "PERSONA" ("ID") ENABLE
/

CREATE TABLE  "PERSONA_LOGROS" 
   (	"ID_PERSONA" NUMBER, 
	"ITEM" NUMBER, 
	"TITULO" VARCHAR2(1000), 
	"DESCRIPCION" VARCHAR2(2000), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   )
/
ALTER TABLE  "PERSONA_LOGROS" ADD CONSTRAINT "eval_logro_persona_fk" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES  "PERSONA" ("ID") ENABLE
/

CREATE TABLE  "PERSONA_PROYECTOS" 
   (	"ID_PERSONA" NUMBER, 
	"ITEM" NUMBER, 
	"LINK" VARCHAR2(1000), 
	"DEMO" BLOB, 
	"ROL" VARCHAR2(1000), 
	"DESCRIPCION" VARCHAR2(2000), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   )
/
ALTER TABLE  "PERSONA_PROYECTOS" ADD CONSTRAINT "eval_proyectos_persona_fk" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES  "PERSONA" ("ID") ENABLE
/